name: 'check dependabot security findings'


on:
    workflow_dispatch:

permissions: read-all

jobs:   
  check-security-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: 'get alerts'
        shell: bash   
        run: |
            echo "${{ github.event.repository.owner.login }}"
            gh api -X GET \
                orgs/${ORGANIZATION}/code-scanning/alerts \
                | jq
            
       
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
  check-specific-alerts:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/github-script@v6
          with:
            script: |
                console.log("-----------------")
                console.log(context)
                console.log("------------------")
