name: "run python script"

on:
    workflow_dispatch:

defaults:
    run: 
        shell: bash
        working-directory: .github/workflows

jobs:
    install-dependencies:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: python testPython.py