name: "run python script"

permissions: read-all
on:
    workflow_dispatch:

defaults:
    run: 
        shell: bash
        working-directory: .github/workflows

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ORGANIZATION: ${{ github.event.repository.owner.login }}
    REPOSITORY: ${{ github.event.repository.name }}
    OWNER: ${{ github.event.repository.owner.login }}
jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                python testPython.py