name: "run python script"

permissions: 
    actions: read
    checks: read
    contents: read
    deployments: read
    id-token: write
    issues: write
    discussions: read
    packages: read
    pages: read
    pull-requests: read
    repository-projects: read
    security-events: read
    statuses: read
on:
    workflow_dispatch:

defaults:
    run: 
        shell: bash
        working-directory: .github/workflows

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ORGANIZATION: ${{ github.event.repository.owner.login }}
    REPOSITORY: ${{ github.event.repository.name }}
    OWNER: ${{ github.event.repository.owner.login }}
jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                python testPython.py